### ISSUE TITLE
openssl download url breaks when new version is released

### ISSUE THREAD

**Issue by jsharpe** [dropbox/dbx_build_tools#8]
When openssl releases a new version, the currently latest version gets moved to source/old/ and hence the url in this repo becomes invalid.
If a list of urls were provided then both urls could be included to prevent build breakages.

**Comment by jsharpe** [comment]
@benjaminp that commit doesn't quite resolve this - you'll need to add the source/old variant of the openssl url into the list as well as the current one to ensure it continues to work

**Comment by benjaminp** [comment]
We are usually careful to stay up to date with OpenSSL releases because of security. Clients may, of course, pass whatever url lists in they desire.

(It sure would be great if OpenSSL had perma urls.)
